config/routes.rb
Rails.application.routes.draw do
  resources :things

  resources :projects do
    resources :things
  end

  devise_for :users
  root to: 'static#index'

  get 'api/p/:project_id/ping', to: 'things#ping'
  get 'api/p/:project_id/:id', to: 'things#get_api'
  post 'api/p/:project_id', to: 'things#post_api'
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :things
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects

  before_create :assign_token

  def assign_token
    self.auth_token = SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # CORS filters
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, Accept, Origin, Referrer, User-Agent'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end


  def authenticate_user_from_token!
    if current_user.nil?
      render json: {
        message: 'Unauthorized request'
      }, status: 401
    end
  end

  def current_user
    if token = params[:auth_token]
      User.find_by_auth_token token
    else
      super
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.all
  end

  def new
    @project = current_user.projects.new
  end

  def show
    @project = current_user.projects.friendly.find params[:id]
  end

  def create
    @project = current_user.projects.new(obj_params)

    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  private

  def obj_params
    params.require(:project).permit :name
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'landing'

  def index
    if user_signed_in?
      redirect_to projects_path
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :authenticate_user_from_token!, only: [:get_api, :post_api]
  before_action :authenticate_user!, except: [:get_api, :post_api, :ping]
  before_action :set_project, except: :ping

  def index
    @things = @project.things
  end

  def new
    @thing = @project.things.new
  end

  def show
    @thing = @project.things.friendly.find params[:id]
  end

  def create
    @thing = @project.things.new(obj_params)

    if @thing.save
      redirect_to project_things_path(@project)
    else
      render :new
    end
  end

  def ping
    user = User.find_by_auth_token(params[:auth_token])
    render text: (user.nil? ? nil : 'pong')
  end

  def get_api
    @thing = @project.things.friendly.find params[:id]
    value = JSON.parse(@thing.value) rescue {}
    render json: value
  end

  def post_api
    @thing = @project.things.where(name: obj_params[:name]).first_or_initialize
    @thing.value = params.require(:thing)[:value].to_json

    if @thing.save
      render json: @thing.to_json
    else
      render json: @thing.errors.full_messages
    end
  end

  private

  def obj_params
    params.require(:thing).permit :name, :value
  end

  def set_project
    @project = current_user.projects.friendly.find params[:project_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Darna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'partials/nav' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <%= render 'partials/head_contents' %>
  <body class="landing">

    <%= render 'partials/nav' %>
    <%= yield %>

  </body>
</html>

app/views/partials/_head_contents.html.erb
<head>
  <title>Darna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>

app/views/partials/_nav.html.slim
nav.navbar.navbar-default role="navigation" 
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Darna", root_path, class: "navbar-brand"
    /! Collect the nav links, forms, and other content for toDarna!
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in? 
          li
            = link_to 'Projects', projects_path
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#" 
              = current_user.email
              span.caret
            ul.dropdown-menu role="menu" 
              /li
                a href="#"  Action
              /li.divider
              li
                = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Login', new_user_session_path
          li
            = link_to 'Create Account', new_user_registration_path
    /! /.navbar-collapse
  /! /.container-fluid

app/views/projects/_form.slim
= form_for project do |f|
  = f.label :name
  = f.text_field :name
  = f.submit :Save

app/views/projects/index.slim
.row
  .col-md-12
    h1 Your Projects
  .col-md-8
    - for p in @projects
      div.project-div
        h2
          = link_to p.name, p
    h2
      = link_to 'Create a new project', new_project_path, class: "btn btn-primary"
  .col-md-4
    .well
      p.lead Keep your token safe and secure!
    pre
      'API Token:
      br
      = current_user.auth_token

app/views/projects/new.slim
h1 New Project
= render 'form', project: @project

app/views/projects/show.slim
.row
  .col-md-12
    h1= @project.name
    p= "Project ID: #{@project.slug}"

app/views/things/_form.slim
= form_for [@project, thing] do |f|
  = f.label :name
  = f.text_field :name
  br
  = f.label :value
  = f.text_area :value
  br
  = f.submit :Save

app/views/things/index.slim
- for t in @things
  = t.value
  br

app/views/things/new.slim
h1 New Things

= render 'form', thing: @thing

app/views/things/show.slim
h1 d thing
= @thing.inspect